namespace Word2Chm.Core.Model;

/// <summary>
/// Intermediate representation of the source Word document, produced by the DOCX
/// parser and consumed by the generators. It intentionally keeps the document
/// structure close to what Word stores, so that layout decisions stay in the
/// generator layer rather than in the parser.
/// </summary>
public abstract class DocumentBlock
{
    /// <summary>Anchor assigned to this block, generated by the builder when needed.</summary>
    public string? Anchor { get; set; }

    /// <summary>Word bookmark names attached to this block.</summary>
    public List<string> Bookmarks { get; } = new();
}

/// <summary>A heading paragraph. Level 1 headings start a new HTML page.</summary>
public sealed class HeadingBlock : DocumentBlock
{
    public int Level { get; set; }

    /// <summary>Visible heading text, with any context ID marker removed.</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>Symbolic context ID declared with the <c>{#...}</c> marker, if any.</summary>
    public string? Symbol { get; set; }

    /// <summary>Numeric context ID declared as <c>{#SYMBOL=123}</c>, if any.</summary>
    public int? ExplicitId { get; set; }

    public List<InlineNode> Inlines { get; } = new();

    /// <summary>Word index entry keywords declared by an XE field in this heading.</summary>
    public List<IndexKeyword> IndexKeywords { get; } = new();
}

/// <summary>A regular paragraph.</summary>
public sealed class ParagraphBlock : DocumentBlock
{
    /// <summary>Word paragraph style identifier, used for style-driven mapping.</summary>
    public string? StyleId { get; set; }

    public int OutlineLevel { get; set; } = -1;

    public List<InlineNode> Inlines { get; } = new();

    /// <summary>Image filename when the paragraph consists of a single image.</summary>
    public string? ImageFileName { get; set; }

    /// <summary>Word index entry keywords declared by an XE field in this paragraph.</summary>
    public List<IndexKeyword> IndexKeywords { get; } = new();
}

/// <summary>A bulleted or numbered list, flat with per-item nesting level.</summary>
public sealed class ListBlock : DocumentBlock
{
    public bool Ordered { get; set; }
    public List<ListItem> Items { get; } = new();
}

public sealed class ListItem
{
    /// <summary>Zero-based indent level coming from the Word numbering definition.</summary>
    public int Level { get; set; }

    public List<InlineNode> Inlines { get; } = new();
}

/// <summary>A table with header detection and per-cell block content.</summary>
public sealed class TableBlock : DocumentBlock
{
    public List<TableRow> Rows { get; } = new();
    public bool HasHeaderRow { get; set; }
}

public sealed class TableRow
{
    public List<TableCell> Cells { get; } = new();
}

public sealed class TableCell
{
    public List<DocumentBlock> Blocks { get; } = new();
    public int GridSpan { get; set; } = 1;
}

/// <summary>A code listing, produced by a monospaced paragraph style.</summary>
public sealed class CodeBlock : DocumentBlock
{
    public string Text { get; set; } = string.Empty;
    public string? Language { get; set; }
}

/// <summary>A standalone image, possibly with a caption.</summary>
public sealed class ImageBlock : DocumentBlock
{
    public string FileName { get; set; } = string.Empty;
    public string? Caption { get; set; }
    public int Width { get; set; }
    public int Height { get; set; }
}

/// <summary>An explicit page break found in the document flow.</summary>
public sealed class PageBreakBlock : DocumentBlock
{
}

public abstract class InlineNode
{
}

/// <summary>A formatted run of text.</summary>
public sealed class TextInline : InlineNode
{
    public string Text { get; set; } = string.Empty;
    public bool Bold { get; set; }
    public bool Italic { get; set; }
    public bool Underline { get; set; }
    public bool Strike { get; set; }
    public bool Superscript { get; set; }
    public bool Subscript { get; set; }
    public string? StyleId { get; set; }

    /// <summary>Inline image file name, when the run embeds a picture.</summary>
    public string? ImageFileName { get; set; }
}

/// <summary>A hyperlink wrapping a sequence of runs.</summary>
public sealed class HyperlinkInline : InlineNode
{
    /// <summary>External URL, when the link targets the web.</summary>
    public string? ExternalUrl { get; set; }

    /// <summary>Word bookmark name, when the link targets a location in the document.</summary>
    public string? BookmarkName { get; set; }

    public List<InlineNode> Children { get; } = new();
}

/// <summary>A line break (<c>w:br</c>) inside a paragraph.</summary>
public sealed class LineBreakInline : InlineNode
{
}

/// <summary>An index entry keyword extracted from a Word XE field.</summary>
public sealed class IndexKeyword
{
    public string Keyword { get; set; } = string.Empty;
    public string? SubKeyword { get; set; }
}
